server:
  port: 8008

spring:
    datasource:
#        name: test

#        开发库
        url: jdbc:mysql://10.1.12.130:3306/thdpzs
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: Asdzx_123
#        url: jdbc:mysql://10.0.30.201:3306/thdpzs?useUnicode=true&characterEncoding=UTF-8
#        driver-class-name: com.mysql.jdbc.Driver
#        username: wdth
#        password: wdth@2
#
#        wdth
#        wdth@2

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.qdjxd.wdth01.model  # 注意：对应实体类的路径
  configuration:
#  输出sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

thymeleaf:
  cache:false
